server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8

spring:
  main:
    allow-circular-references: true

  datasource:
#    jdbc-url: jdbc:mysql://c24host.cafe24.com:3306/c24host?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Seoul
    jdbc-url: jdbc:log4jdbc:mysql://myasset.ddns.net:3306/myasset?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Seoul
    username: myasset
    password: dba3048!01
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

